# Generated by Django 4.2.2 on 2023-07-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
